setting:
  name: "rgbd_batch"
  output_root: "./experiments/"
  pc_path: "xxx/data/neural_rgbd_data/green_room_kitti_format/rgbd_ply"
  pose_path: "xxx/data/neural_rgbd_data/green_room_kitti_format/poses.txt"
  calib_path: ""
  load_model: False
  model_path: "" 
  first_frame_ref: False
  begin_frame: 0
  end_frame: 1500
  every_frame: 5 # 1 means does not skip
  device: "cuda"
  gpu_id: "0"
process:
  min_range_m: 0.2
  pc_radius_m: 5.0  # distance filter for each frame
  rand_downsample: False # use random or voxel downsampling
  vox_down_m: 0.01
  rand_down_r: 0.2
sampler:
  surface_sample_range_m: 0.05
  surface_sample_n: 3
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 0.3
  free_sample_n: 3
octree:
  leaf_vox_size: 0.02
  tree_level_world: 12
  tree_level_feat: 4
  feature_dim: 8
  poly_int_on: True
  octree_from_surface_samples: True
decoder:
  mlp_level: 2
  mlp_hidden_dim: 32
  freeze_after_frame: 0
loss:
  ray_loss: False
  main_loss_type: sdf_bce  # select from sdf_bce (our proposed), sdf_l1, sdf_l2, dr, dr_neus
  sigma_sigmoid_m: 0.02
  loss_weight_on: False
  behind_dropoff_on: False
  ekional_loss_on: False
  weight_e: 0.1
continual:
  continual_learning_reg: False # using incremental mapping with regularization
  lambda_forget: 0 
  window_replay_on: False # replay within the sliding window
  window_radius_m: 0
optimizer:
  iters: 20000
  batch_size: 4096
  learning_rate: 0.01
  weight_decay: 1e-7 # l2 regularization
eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: True # visualize the mapping or not
  vis_freq_iters: 5000 # reconstruct the mesh every x iterations
  save_freq_iters: 10000 # save the model and octree every x iterations
  mesh_freq_frame: 1
  mc_res_m: 0.01 # reconstruction marching cubes resolution
  mc_with_octree: True # querying sdf in the map bbx
  mc_vis_level: 2
  save_map: False # save the sdf map or not 
